[package]
name = "rbars"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
toml = "0.4"
handlebars = { version = "1", default-features = false, features = ['no_dir_source'] }
serde_json = "1"
